// Mirrors mobile app types - keeps Supabase rows shape-compatible across platforms.
// IMPORTANT: column names here MUST match what's in the Supabase DB. The mobile
// app's `src/types/index.ts` is the source of truth.

export type BusinessType =
  | "nail_tech"
  | "makeup_artist"
  | "tutor"
  | "photographer"
  | "personal_trainer"
  | "freelancer"
  | "event_planner"
  | "repair_tech"
  | "home_service"
  | "other";

export type SubscriptionStatus = "free" | "pro" | "trial";

export type ClientStatus = "active" | "follow_up" | "overdue" | "inactive";

export type PaymentType = "deposit" | "full" | "partial" | "retainer";
export type PaymentStatus = "paid" | "pending" | "overdue" | "partial" | "failed" | "refunded";
// Providers for client-facing invoice payment links. The Orbit user (business
// owner) connects ONE of these with their own merchant keys; payments land in
// their account, not Orbit's.
export type PaymentProvider = "lemonsqueezy" | "flutterwave";

export type BookingStatus = "confirmed" | "pending" | "cancelled" | "completed";

export type RepeatType = "never" | "daily" | "weekly" | "monthly";

export interface UserProfile {
  id: string;
  email: string;
  full_name: string;
  business_name: string | null;
  business_type: BusinessType;
  subscription_status: SubscriptionStatus;
  trial_ends_at: string | null;
  avatar_url: string | null;
  created_at: string;
}

export interface Client {
  id: string;
  user_id: string;
  name: string;
  phone: string;
  whatsapp_number: string;
  email: string | null;
  business_type: BusinessType;
  notes: string | null;
  preferences: string | null;
  birthday: string | null;
  status: ClientStatus;
  last_contacted: string | null;
  total_paid: number;
  outstanding_balance: number;
  created_at: string;
  updated_at: string;
}

export interface InvoiceLineItem {
  id: string;
  description: string;
  amount: number;
}

export interface Payment {
  id: string;
  user_id: string;
  client_id: string;
  client_name: string;
  amount: number;
  paid_amount: number | null;
  remaining_balance: number | null;
  type: PaymentType;
  status: PaymentStatus;
  date: string;             // Due date
  notes: string | null;
  // Invoice fields
  invoice_number: string | null;
  line_items: InvoiceLineItem[] | null;
  // Online payment
  payment_link: string | null;
  transaction_reference: string | null;
  payment_provider: PaymentProvider | null;
  webhook_verified: boolean | null;
  payment_completed_at: string | null;
  created_at: string;
}

export interface Booking {
  id: string;
  user_id: string;
  client_id: string;
  client_name: string;
  date: string;             // ISO date string "2026-05-20"
  time: string;             // 24h time string "14:30"
  title: string;            // Was "service" - DB column is `title`
  notes: string | null;
  status: BookingStatus;
  business_type: BusinessType;
  created_at: string;
  updated_at: string;
}

/**
 * In-app notification (bell dropdown). Generated by server events:
 * new public bookings, payment received, invoice overdue, trial ending, etc.
 */
export type NotificationType =
  | "booking_received"      // someone booked via public link
  | "booking_confirmed"     // owner confirmed a pending booking
  | "booking_cancelled"     // owner cancelled a booking
  | "payment_received"      // an invoice was paid
  | "invoice_overdue"       // an invoice is now overdue
  | "reminder_due"          // a reminder is due
  | "trial_ending"          // Pro trial ending soon
  | "trial_expired"         // trial just ended
  | "subscription_renewed"  // billing cycle renewed
  | "subscription_failed"   // payment for subscription failed
  | "client_birthday"       // a client's birthday is today
  | "welcome";              // new account

export interface NotificationRow {
  id: string;
  user_id: string;
  type: NotificationType;
  title: string;
  body: string | null;
  action_url: string | null;
  is_read: boolean;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

export interface Reminder {
  id: string;
  user_id: string;
  client_id: string | null;
  client_name: string | null;
  message: string;          // Was "title" - DB column is `message`
  due_date: string;         // Was "due_at" - DB column is `due_date`
  is_done: boolean;
  repeat_type: RepeatType;
  created_at: string;
}

// ── AI Assistant chat history ──────────────────────────────────────────────
export interface AiMessage {
  role: "user" | "assistant";
  content: string;
}

export interface AiConversation {
  id: string;
  user_id: string;
  title: string;
  messages: AiMessage[];
  created_at: string;
  updated_at: string;
}

export const BUSINESS_TYPE_LABELS: Record<BusinessType, string> = {
  nail_tech: "Nail Tech",
  makeup_artist: "Makeup Artist",
  tutor: "Tutor",
  photographer: "Photographer",
  personal_trainer: "Personal Trainer",
  freelancer: "Freelancer",
  event_planner: "Event Planner",
  repair_tech: "Repair Tech",
  home_service: "Home Service",
  other: "Other",
};

/** What we call "a booking" depends on the kind of business. */
export const BOOKING_TITLE_LABELS: Record<BusinessType, string> = {
  nail_tech:        "Service",
  makeup_artist:    "Session",
  tutor:            "Session",
  photographer:     "Shoot",
  personal_trainer: "Training session",
  freelancer:       "Project",
  event_planner:    "Event",
  repair_tech:      "Job",
  home_service:     "Job",
  other:            "Appointment",
};

/**
 * A service the business owner offers. Lives inside
 * profiles.booking_link.services as a JSON array. Clients pick from this list
 * on the public booking page; the owner also picks from it when creating
 * bookings or invoices internally.
 */
export interface Service {
  name: string;
  duration_minutes: number;
  /** Free-form price string (so owners can write "$80", "Free", "From N5,000"). */
  price: string;
}

/**
 * Sensible starter services per business type. We pre-fill the welcome wizard
 * with these so new accounts don't see an empty list; the owner can edit /
 * remove anything they don't offer.
 */
export const DEFAULT_SERVICES_BY_TYPE: Record<BusinessType, Service[]> = {
  nail_tech: [
    { name: "Classic manicure",        duration_minutes: 45, price: "" },
    { name: "Gel pedicure",            duration_minutes: 60, price: "" },
    { name: "Acrylic full set",        duration_minutes: 90, price: "" },
  ],
  makeup_artist: [
    { name: "Soft glam",               duration_minutes: 60, price: "" },
    { name: "Full bridal makeup",      duration_minutes: 120, price: "" },
    { name: "Photoshoot look",         duration_minutes: 75, price: "" },
  ],
  tutor: [
    { name: "1-on-1 tutoring",         duration_minutes: 60, price: "" },
    { name: "Group session",           duration_minutes: 90, price: "" },
    { name: "Exam prep session",       duration_minutes: 60, price: "" },
  ],
  photographer: [
    { name: "Portrait session",        duration_minutes: 60, price: "" },
    { name: "Event coverage (per hr)", duration_minutes: 60, price: "" },
    { name: "Mini shoot",              duration_minutes: 30, price: "" },
  ],
  personal_trainer: [
    { name: "1-on-1 training",         duration_minutes: 60, price: "" },
    { name: "Small group class",       duration_minutes: 45, price: "" },
    { name: "Consultation",            duration_minutes: 30, price: "Free" },
  ],
  freelancer: [
    { name: "Discovery call",          duration_minutes: 30, price: "Free" },
    { name: "Project consultation",    duration_minutes: 60, price: "" },
    { name: "Hourly rate",             duration_minutes: 60, price: "" },
  ],
  event_planner: [
    { name: "Initial consultation",    duration_minutes: 45, price: "Free" },
    { name: "Full event planning",     duration_minutes: 60, price: "" },
    { name: "Day-of coordination",     duration_minutes: 60, price: "" },
  ],
  repair_tech: [
    { name: "Diagnostic visit",        duration_minutes: 45, price: "" },
    { name: "Standard repair",         duration_minutes: 90, price: "" },
    { name: "Emergency callout",       duration_minutes: 60, price: "" },
  ],
  home_service: [
    { name: "Standard visit",          duration_minutes: 60, price: "" },
    { name: "Deep clean / overhaul",   duration_minutes: 180, price: "" },
    { name: "Quote / inspection",      duration_minutes: 30, price: "Free" },
  ],
  other: [
    { name: "Consultation",            duration_minutes: 30, price: "" },
    { name: "Standard session",        duration_minutes: 60, price: "" },
  ],
};
